# Generated by Django 3.0 on 2019-12-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicesub',
            options={'verbose_name': '选择题', 'verbose_name_plural': '选择题'},
        ),
        migrations.AlterModelOptions(
            name='fillbanksub',
            options={'verbose_name': '填空题', 'verbose_name_plural': '填空题'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': '题目类型', 'verbose_name_plural': '题目类型'},
        ),
        migrations.AlterModelOptions(
            name='topicinfo',
            options={'verbose_name': '题库信息', 'verbose_name_plural': '题库信息'},
        ),
        migrations.AlterModelOptions(
            name='topictype',
            options={'verbose_name': '题库类型', 'verbose_name_plural': '题库类型'},
        ),
    ]
