# Generated by Django 2.2.3 on 2019-12-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicapp', '0002_auto_20191212_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinfo',
            name='qtype',
            field=models.SmallIntegerField(choices=[(0, '技术类'), (1, '教育类'), (2, '文化类'), (3, '常识类'), (4, '地理类'), (5, '体育类'), (6, '面试类'), (7, '热门题库')], default=7, help_text='题库类型', verbose_name='题库类型'),
        ),
        migrations.DeleteModel(
            name='TopicType',
        ),
    ]
