# Generated by Django 2.2.3 on 2019-12-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20191222_2245'),
        ('topicapp', '0003_auto_20191222_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicinfo',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.AuthUser'),
            preserve_default=False,
        ),
    ]
