# Generated by Django 3.0 on 2019-12-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态', verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uemail', models.EmailField(db_index=True, help_text='邮箱', max_length=64, unique=True, verbose_name='邮箱')),
                ('uname', models.CharField(help_text='用户名', max_length=10, unique=True, verbose_name='用户名')),
                ('upasswd', models.CharField(help_text='密码', max_length=32, verbose_name='密码')),
                ('isauth', models.BooleanField(default=0, help_text='是否认证', null=True, verbose_name='是否认证')),
                ('isdelete', models.BooleanField(default=0, help_text='是否已删除', null=True, verbose_name='是否已删除')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态', verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uaddr', models.CharField(help_text='用户住址', max_length=128, null=True, verbose_name='用户住址')),
                ('uschool', models.CharField(help_text='毕业院校', max_length=20, null=True, verbose_name='毕业院校')),
                ('ugender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, help_text='性别', verbose_name='性别')),
                ('uage', models.IntegerField(help_text='年龄', null=True, verbose_name='年龄')),
                ('umobile', models.CharField(help_text='手机号', max_length=11, null=True, verbose_name='手机号')),
                ('uweixin', models.CharField(help_text='微信号', max_length=20, null=True, verbose_name='微信号')),
                ('uidentify', models.CharField(help_text='身份证号', max_length=18, null=True, verbose_name='身份证号')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态', verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('oemail', models.EmailField(help_text='邮箱', max_length=64, unique=True, verbose_name='邮箱')),
                ('oname', models.CharField(help_text='公司名称', max_length=32, unique=True, verbose_name='公司名称')),
                ('oreluname', models.CharField(help_text='真实姓名', max_length=5, verbose_name='真实姓名')),
                ('oumobile', models.DecimalField(decimal_places=0, help_text='认证手机号', max_digits=11, verbose_name='认证手机号')),
                ('otype', models.IntegerField(choices=[(0, '互联网IT'), (1, '金融'), (2, '房地产/建筑'), (3, '贸易/零售/物流'), (4, '教育/传媒/广告'), (5, '服务业'), (6, '市场/销售'), (7, '人事/财务/行政'), (8, '其他')], default=4, help_text='公司类型', verbose_name='公司类型')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.RegUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
