# Generated by Django 3.0 on 2019-12-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'verbose_name': '机构用户', 'verbose_name_plural': '机构用户'},
        ),
        migrations.AlterModelOptions(
            name='reguser',
            options={'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户其他信息', 'verbose_name_plural': '用户其他信息'},
        ),
    ]
