# Generated by Django 2.2.3 on 2019-12-17 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_emailverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='oreluname',
            field=models.CharField(help_text='真实姓名', max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 18, 57, 52, 358018), verbose_name='发送时间'),
        ),
    ]
