# Generated by Django 2.2.3 on 2019-12-22 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20191217_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 10, 14, 33, 528823), verbose_name='发送时间'),
        ),
    ]
