# Generated by Django 2.2.3 on 2019-12-23 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20191222_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 19, 41, 33, 495180), verbose_name='发送时间'),
        ),
    ]
