# Generated by Django 2.2.3 on 2019-12-23 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20191223_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 20, 4, 35, 903548), verbose_name='发送时间'),
        ),
    ]
