# Generated by Django 2.2.3 on 2019-12-28 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20191223_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authuser', to='userapp.RegUser'),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 23, 22, 2, 363393), verbose_name='发送时间'),
        ),
    ]
