# Generated by Django 2.2.3 on 2019-12-30 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20191228_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ugender',
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 21, 51, 24, 573956), verbose_name='发送时间'),
        ),
    ]
