# Generated by Django 2.2.3 on 2019-12-30 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_auto_20191230_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uidentify',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uemail',
            field=models.CharField(help_text='邮箱', max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uname',
            field=models.CharField(help_text='答题者', max_length=20, null=True, verbose_name='答题者'),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 23, 32, 40, 389972), verbose_name='发送时间'),
        ),
    ]
