# Generated by Django 2.2.3 on 2019-12-30 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20191230_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 23, 35, 21, 627634), verbose_name='发送时间'),
        ),
    ]
