# Generated by Django 2.2.3 on 2019-12-30 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_auto_20191230_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ugender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=0, help_text='性别', null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 23, 59, 2, 503660), verbose_name='发送时间'),
        ),
    ]
