# Generated by Django 2.2.3 on 2019-12-31 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_auto_20191230_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 13, 16, 14, 178084), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ugender',
            field=models.CharField(help_text='性别', max_length=5, null=True, verbose_name='性别'),
        ),
    ]
