# Generated by Django 2.2.3 on 2020-01-02 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0007_remove_matchreport_userinfo'),
        ('userapp', '0015_auto_20200102_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='reguser',
            name='uaddr',
            field=models.CharField(help_text='用户住址', max_length=128, null=True, verbose_name='用户住址'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='uage',
            field=models.IntegerField(help_text='年龄', null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='ugender',
            field=models.CharField(help_text='性别', max_length=5, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='uid',
            field=models.CharField(help_text='身份证号', max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='umobile',
            field=models.CharField(help_text='手机号', max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='uschool',
            field=models.CharField(help_text='毕业院校', max_length=20, null=True, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='uweixin',
            field=models.CharField(help_text='微信号', max_length=20, null=True, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 14, 34, 3, 971063), verbose_name='发送时间'),
        ),
    ]
