# Generated by Django 2.2.3 on 2020-01-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_auto_20200103_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 17, 33, 20, 801751), verbose_name='发送时间'),
        ),
    ]
