# Generated by Django 3.0 on 2019-12-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('topicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(0, '已完成'), (1, '未完成'), (2, '超时')], default=1, help_text='答题状态', verbose_name='答题状态')),
                ('question_record', models.CharField(help_text='问题记录', max_length=10000, null=True, verbose_name='问题记录')),
                ('answer_record', models.CharField(help_text='答案记录', max_length=10000, null=True, verbose_name='答案记录')),
                ('stime', models.DateTimeField(default=0, help_text='答题开始时间', null=True, verbose_name='答题开始时间')),
                ('etime', models.DateTimeField(default=0, help_text='答题结束时间', null=True, verbose_name='答题结束时间')),
                ('right_list', models.CharField(help_text='正确的题目', max_length=10000, null=True, verbose_name='正确题目')),
                ('error_list', models.CharField(help_text='错误的题目', max_length=10000, null=True, verbose_name='错误的题目')),
                ('right_count', models.IntegerField(default=0, help_text='答对总题数', verbose_name='答对总题数')),
                ('error_count', models.IntegerField(default=0, help_text='答错总题数', verbose_name='答错总题数')),
                ('question_count', models.IntegerField(default=0, help_text='总题数', verbose_name='总题数')),
                ('usedtime', models.DecimalField(decimal_places=1, help_text='答题用时', max_digits=2, verbose_name='答题用时')),
                ('resgrade', models.SmallIntegerField(help_text='考试成绩', verbose_name='考试成绩')),
                ('baseuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.RegUser')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态', verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('mname', models.CharField(help_text='比赛名称', max_length=20, unique=True, verbose_name='比赛名称')),
                ('mtime', models.SmallIntegerField(default=0, help_text='设置比赛时间', verbose_name='设置比赛时间')),
                ('topicount', models.SmallIntegerField(default=10, help_text='总题数', verbose_name='总题数')),
                ('score', models.SmallIntegerField(default=100, help_text='总分数', verbose_name='总分数')),
                ('stime', models.DateTimeField(help_text='比赛开始时间', verbose_name='比赛开始时间')),
                ('etime', models.DateTimeField(help_text='比赛截止时间', verbose_name='比赛截止时间')),
                ('uname', models.BooleanField(default=0, help_text='用户名', null=True, verbose_name='用户名')),
                ('uaddr', models.BooleanField(default=0, help_text='用户住址', null=True, verbose_name='用户住址')),
                ('uemail', models.BooleanField(default=0, help_text='邮箱', null=True, verbose_name='邮箱')),
                ('uschool', models.BooleanField(default=0, help_text='毕业院校', null=True, verbose_name='毕业院校')),
                ('ugender', models.BooleanField(default=0, help_text='性别', null=True, verbose_name='性别')),
                ('uage', models.BooleanField(default=0, help_text='年龄', null=True, verbose_name='年龄')),
                ('umobile', models.BooleanField(default=0, help_text='手机号', null=True, verbose_name='手机号')),
                ('uweixin', models.BooleanField(default=0, help_text='微信', null=True, verbose_name='微信')),
                ('uid', models.BooleanField(default=0, help_text='身份证号', null=True, verbose_name='身份证号')),
                ('option_fields', models.TextField(help_text='下拉框字段选项配置，#号隔开，每个字段由:h和，号组成。 如 option1:吃饭，喝水，睡觉#option2:上班，学习，看电影', max_length=255, null=True, verbose_name='下拉框字段')),
                ('auinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.AuthUser')),
                ('qinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicapp.TopicInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
