# Generated by Django 3.0 on 2019-12-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='curmatch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='matchapp.MatchConfig'),
            preserve_default=False,
        ),
    ]
