# Generated by Django 3.0 on 2019-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_matchreport_curmatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchconfig',
            options={'verbose_name': '配置比赛', 'verbose_name_plural': '配置比赛'},
        ),
        migrations.AlterModelOptions(
            name='matchreport',
            options={'verbose_name': '答题结果', 'verbose_name_plural': '答题结果'},
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='answer_record',
            field=models.TextField(help_text='答案记录', max_length=10000, null=True, verbose_name='答案记录'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='question_record',
            field=models.TextField(help_text='问题记录', max_length=10000, null=True, verbose_name='问题记录'),
        ),
    ]
