# Generated by Django 2.2.3 on 2019-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0003_auto_20191213_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchconfig',
            name='isaddinfo',
            field=models.BooleanField(default=0, help_text='是否添加其他信息', verbose_name='是否添加其他信息'),
        ),
        migrations.AddField(
            model_name='matchconfig',
            name='mregular',
            field=models.TextField(default='', help_text='比赛规则', max_length=100, verbose_name='比赛规则'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchconfig',
            name='option_fields',
            field=models.TextField(help_text='下拉框字段选项配置，,号隔开，每个字段由:和#号组成。如 name:vervbose:吃饭#喝水#睡觉，name:verbose:上班#学习#看电影', max_length=255, null=True, verbose_name='下拉框字段'),
        ),
    ]
