# Generated by Django 2.2.3 on 2019-12-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0004_auto_20191228_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchconfig',
            name='mtime',
            field=models.SmallIntegerField(default=0, help_text='考试总时间', verbose_name='考试总时间'),
        ),
    ]
