# Generated by Django 2.2.3 on 2020-01-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0006_remove_matchconfig_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreport',
            name='userinfo',
        ),
    ]
