# Generated by Django 2.2.3 on 2020-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0008_auto_20200103_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='his_rank',
            field=models.CharField(help_text='历史排序', max_length=100, null=True, verbose_name='历史排名'),
        ),
    ]
